### ISSUE TITLE
Version 0.1.2 Broken in Chrome and Firefox (missing index.html?)

### ISSUE THREAD

**Issue by vegeta897** [MozillaReality/ecsy-devtools#67]
After updating my extension in Chrome to version 0.1.2, the ECSY tab in my devtools is blank.

Chrome:
![image](https://user-images.githubusercontent.com/1789096/89721885-88c05900-d9b0-11ea-8a49-57c1eb66ab07.png)

Firefox:
![image](https://user-images.githubusercontent.com/1789096/89721905-a2fa3700-d9b0-11ea-81da-44b4b1302b54.png)

Firefox was a fresh install of the extension (not an update) and I had a friend do a fresh install on Chrome with the same results.

The "detected" page that shows when clicking the extension button is working in Chrome:
![image](https://user-images.githubusercontent.com/1789096/89721932-02f0dd80-d9b1-11ea-85ee-a47748409814.png)

But not in FF: `Firefox can’t find the file at moz-extension://123f8dc6-d396-4023-ac7b-1585b5b7eb80/src/extension/src/extension/popups/detected.html.`

Despite the missing views, the extension seems to still be "working" in the background, since the errors I reported in #66 are still throwing in the console when using pooled components.

**Comment by briancw** [comment]
For anyone stuck without the dev tools here's how to get it running locally.
1. git clone this repository and install it's dependencies with npm (or your favorite package manager)
2. run 'npm run production'
3. Navigate to chrome://extensions
4. Remove the currently installed ecsy-devtools if you have it installed already
5. enable developer mode in the top right corner
6. click "Load unpacked" and navigate to wherever you cloned the project to

Hope this helps someone. I know I was missing this invaluable resource till I figured out how to get it working again.

**Comment by robertlong** [comment]
@fernandojsg whenever you have time, can you look into this?

**Comment by fernandojsg** [comment]
@vegeta897 @briancw @robertlong could you please give it a try in firefox https://addons.mozilla.org/en-US/firefox/addon/ecsy-devtools/
I just pushed a new release, it will be soon available also on chrome but the review process is a bit longer there.
Thanks!

**Comment by briancw** [comment]
@fernandojsg Looks to be working again. Thank you for updating this.

**Comment by vegeta897** [comment]
Thanks @fernandojsg, but I am still having issues.

To start with, clicking on the ESCY devtools icon in the extension list in the top right of the browser still fails to load that "detected" view, as pointed out in the original issue post.

More importantly, the extension is still broken when using non-pooled components. Please see my updated issue #66 where I point out the part of the code that is guaranteed to throw errors when registering a component without pooling. I have also updated it with observed behavior in the newest release.
